dist: trusty
sudo: require

language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install pep8
    - pip install autopep8

install:
    - pip install -r requirements.txt
    - pip install codecov # codecov isn't really part of our project, just
                          # a useful metric

script:
    - flake8 .
    - nosetests . -v --with-coverage

after_success:
    - codecov
