dist: trusty

language: python

branches:
    only:
        - master

cache: pip

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - pip install --upgrade pip
    - pip install pep8
    - pip install autopep8

script:
    - ./scripts/test.sh
